const ALLOWED_ORIGIN = "https://arst-calcolo-tratte.github.io";
const MODEL = "gpt-5.6-luna";
const BUILD = "2026-09-17-v5";

const SYSTEM_MARIO = `Sei il motore di ricerca dell'app "Assistente Entrate Extra".
Cerca opportunità REALI e RECENTI per una persona che vuole costruire circa 300 euro al mese in modo legale.

REGOLA ASSOLUTA: la compatibilità con il profilo reale viene prima del numero di risultati.
PROFILO REALE: autista NCC e autobus turistici, Patente D/CQC, esperienza nel trasporto e turismo, conoscenza della Sardegna, uso normale di strumenti digitali. Può creare semplici pagine/web app ma NON è un professionista sviluppatore, social media manager, marketer o consulente. Nessuna partita IVA dichiarata. Ha già un lavoro principale da autista ARST: NON cercare altri lavori da autista/conducente.

NON PROPORRE: autista, conducente, driver, NCC, autobus, pullman o trasporto professionale; social media manager, digital marketing, SEO, marketing; sviluppatore/programmatore, web designer professionista, grafico professionista; consulente, commerciale, agente commerciale, procacciatore, venditore; commercialista, contabile, insegnante o professioni qualificate; ruoli che richiedono laurea, albo, abilitazione o partita IVA obbligatoria; lavori pesanti non compatibili; trading, scommesse, MLM, investimenti o richieste di pagamento anticipato.

CERCA CON PRIORITÀ: richieste concrete di privati, attività e strutture per supporto operativo leggero, turismo/ospitalità, accoglienza semplice, front office, piccoli incarichi locali, logistica leggera, part-time o occasionale conciliabile con il lavoro principale. Cerca soprattutto "cerco persona", "cerco qualcuno", "cercasi", "cerco aiuto", "offro lavoro", "part-time", "lavoro occasionale".
Non inventare annunci, aziende, compensi, requisiti o URL. Per aspetti fiscali/contrattuali non espliciti usa "Da verificare". La soglia contributiva di 5.000 euro non rende automaticamente regolare o esente un'attività.`;

const SYSTEM_VALERIA = `Sei il motore di ricerca di lavoro dedicato a Valeria. Cerca annunci REALI, RECENTI e VERIFICABILI in Sardegna per una persona appartenente alle categorie protette/collocamento mirato ai sensi della Legge 68/99.

PRIORITÀ ASSOLUTA DELLE FONTI: 1) ASPAL Sardegna e aspalsardegna.it; 2) asp alPOST/aspalPOST, comprese le sezioni "Annunci collocamento mirato L. 68/99" e "Concorsi L. 68/99"; 3) Sardegna Lavoro/CPI; 4) siti aziendali e portali lavoro solo come integrazione. Quando esiste un annuncio ASPAL pertinente, preferiscilo agli annunci generici.

PROFILO: Valeria cerca un lavoro leggero e compatibile con la L.68/99, preferibilmente segreteria, reception, front office, accoglienza utenti/clienti, centralino, back office, supporto amministrativo semplice, inserimento dati o attività di sportello non pesante. Preferisce mansioni che consentano di alternare seduta e movimento. Evitare mansioni prevalentemente in piedi.

ESCLUDI: lavori pesanti, sollevamento/spostamento carichi, magazzino, facchinaggio, produzione pesante, pulizie pesanti, cameriera ai piani, cucina, lavori manuali gravosi, vendita con attività prevalentemente in piedi, mansioni che richiedono attività fisica intensa. Non inventare l'idoneità fisica: se l'annuncio non chiarisce un requisito, indica "Da verificare".

CERCA ESPRESSAMENTE: "L.68/99", "Legge 68/99", "categorie protette", "collocamento mirato", "art. 1", "art. 8", "preselezione L.68/99", "avviamento numerico", "segreteria", "reception", "front office", "accoglienza", "centralino", "back office", "supporto amministrativo", "inserimento dati".

Controlla sempre sede, scadenza, contratto, orario, requisiti e modalità di candidatura. Non inventare annunci, aziende, compensi, requisiti o URL. Se non esistono risultati realmente compatibili, restituisci meno risultati o zero.`;

const JSON_SCHEMA_NOTE = `
Rispondi ESCLUSIVAMENTE con JSON valido:
{"results":[{"title":"titolo annuncio/opportunità","source":"sito o piattaforma","url":"URL reale","searchUrl":"URL utile per verificare la fonte oppure Da verificare","location":"località oppure Online","compensation":"compenso oppure Da verificare","hours":"orario/tempo oppure Da verificare","type":"occasionale | part-time | subordinato | autonomo | collaborazione | altro | Da verificare","partitaIva":"yes | no | unclear","description":"descrizione breve basata sulla fonte","why":"motivo concreto della compatibilità","foundAt":"data oppure Da verificare"}]}
Massimo 8 risultati.`;

function corsHeaders(origin){const allowed=origin===ALLOWED_ORIGIN?origin:ALLOWED_ORIGIN;return {"Access-Control-Allow-Origin":allowed,"Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Content-Type":"application/json; charset=utf-8","Vary":"Origin","Cache-Control":"no-store"};}
function json(data,status,origin){return new Response(JSON.stringify(data),{status,headers:corsHeaders(origin)});}
function extractJson(text){let t=String(text||"").trim();if(t.startsWith("```"))t=t.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();const first=t.indexOf("{");const last=t.lastIndexOf("}");if(first>=0&&last>first)t=t.slice(first,last+1);return JSON.parse(t);}

const HARD_EXCLUDE_MARIO=/social\s*media|digital\s*marketing|marketing\s*(specialist|manager)|seo\s*(specialist|manager)?|commerciale|agente\s+commerciale|procacciatore|venditore|consulente|commercialista|contabile|programmatore|sviluppatore|web\s*designer|web\s*developer|sviluppo\s+software|creazione\s+siti|gestione\s+social|grafico|insegnante|laurea|abilitazione|iscrizione\s+all['’]?albo|partita\s*iva\s*(obbligatoria|required|necessaria)|p\.\s*iva\s*(obbligatoria|required|necessaria)|autista|conducente|driver|ncc|autobus|pullman/i;
const RELEVANT_MARIO=/turismo|hotel|albergo|b&b|struttura\s+ricettiva|accoglienza|front\s*office|reception|supporto\s+operativo|logistica|consegna|corriere|movimentazione|aiuto|occasionale|part[- ]?time/i;
const HARD_EXCLUDE_VALERIA=/magazzino|facchinaggio|sollevamento|carico|scarico|produzione\s+pesante|pulizie\s+pesanti|cameriera\s+ai\s+piani|cucina|lavori?\s+pesanti|mansioni?\s+prevalentemente\s+in\s+piedi|vendita\s+al\s+dettaglio|commesso|operaio/i;
const RELEVANT_VALERIA=/l\.\s*68\s*\/?\s*99|legge\s*68\s*\/?\s*99|categorie\s+protette|collocamento\s+mirato|art\.?\s*(1|8)\b|segreteria|segretar|reception|front\s*office|accoglienza|centralino|back\s*office|supporto\s+amministrativo|amministrativ|inserimento\s+dati|sportello|ufficio|impiegat|part[- ]?time/i;

function filterResults(results,role){const isValeria=role==='valeria';const hard=isValeria?HARD_EXCLUDE_VALERIA:HARD_EXCLUDE_MARIO;const relevant=isValeria?RELEVANT_VALERIA:RELEVANT_MARIO;return results.filter(x=>{const text=[x?.title,x?.description,x?.why,x?.source].filter(Boolean).join(" ");if(hard.test(text))return false;if(!x?.url||!/^https?:\/\//i.test(x.url))return false;return relevant.test(text);}).slice(0,8);}

export default {async fetch(request,env){const origin=request.headers.get("Origin")||ALLOWED_ORIGIN;if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(origin)});if(request.method!=="POST")return json({error:"Metodo non consentito",build:BUILD},405,origin);if(!env.OPENAI_API_KEY)return json({error:"OPENAI_API_KEY non configurata nel Worker",build:BUILD},500,origin);let body;try{body=await request.json();}catch{return json({error:"JSON non valido",build:BUILD},400,origin);}const query=String(body?.query||"").trim();const profile=body?.profile||{};const role=String(profile?.role||'mario').toLowerCase();if(!query)return json({error:"Query mancante",build:BUILD},400,origin);if(query.length>5000)return json({error:"Query troppo lunga",build:BUILD},400,origin);const system=(role==='valeria'?SYSTEM_VALERIA:SYSTEM_MARIO)+JSON_SCHEMA_NOTE;const userPrompt=`PROFILO UTENTE:\n${JSON.stringify(profile,null,2)}\n\nRICHIESTA DI RICERCA:\n${query}\n\nApplica i filtri in modo estremamente rigoroso. Cerca ora sul web e restituisci esclusivamente il JSON richiesto.`;const api=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,tools:[{type:"web_search"}],input:[{role:"system",content:[{type:"input_text",text:system}]},{role:"user",content:[{type:"input_text",text:userPrompt}]}],max_output_tokens:5000})});const raw=await api.text();if(!api.ok){let detail=raw;try{detail=JSON.parse(raw)?.error?.message||raw;}catch{}return json({error:`OpenAI: ${detail}`,build:BUILD},api.status,origin);}let response;try{response=JSON.parse(raw);}catch{return json({error:"Risposta API non valida",build:BUILD},502,origin);}const text=response.output_text||response.output?.map(x=>x.content?.map(c=>c.text||"").join("")).join("")||"";try{const parsed=extractJson(text);const results=filterResults(Array.isArray(parsed.results)?parsed.results:[],role);return json({results,build:BUILD},200,origin);}catch{return json({error:"Il motore ha restituito un formato non interpretabile",raw:text.slice(0,1000),build:BUILD},502,origin);}}};